#############################################################################
# Makefile for building: lightgadu
# Generated by qmake (2.01a) (Qt 4.6.3) on: niedz. lip 18 23:54:30 2010
# Project:  lightgadu.pro
# Template: app
# Command: /usr/bin/qmake -spec /usr/share/qt/mkspecs/linux-g++-64 -unix CONFIG+=debug -o Makefile lightgadu.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_SQL_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -m64 -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -m64 -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt/mkspecs/linux-g++-64 -I. -I/usr/include/QtCore -I/usr/include/QtGui -I/usr/include/QtSql -I/usr/include -I. -I. -I.
LINK          = g++
LFLAGS        = -m64 -Wl,--hash-style=gnu -Wl,--as-needed
LIBS          = $(SUBLIBS)  -L/usr/lib -lgadu -lQtSql -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = contactlistentry.cpp \
		lgaddcontactwindow.cpp \
		lgchatwindow.cpp \
		lgconnectionthread.cpp \
		lgcontactlist.cpp \
		main.cpp \
		mainwindow.cpp \
		lgbuddylistmenu.cpp \
		lgsettingswindow.cpp moc_lgaddcontactwindow.cpp \
		moc_lgchatwindow.cpp \
		moc_lgconnectionthread.cpp \
		moc_lgcontactlist.cpp \
		moc_mainwindow.cpp \
		moc_lgbuddylistmenu.cpp \
		moc_lgsettingswindow.cpp
OBJECTS       = contactlistentry.o \
		lgaddcontactwindow.o \
		lgchatwindow.o \
		lgconnectionthread.o \
		lgcontactlist.o \
		main.o \
		mainwindow.o \
		lgbuddylistmenu.o \
		lgsettingswindow.o \
		moc_lgaddcontactwindow.o \
		moc_lgchatwindow.o \
		moc_lgconnectionthread.o \
		moc_lgcontactlist.o \
		moc_mainwindow.o \
		moc_lgbuddylistmenu.o \
		moc_lgsettingswindow.o
DIST          = /usr/share/qt/mkspecs/common/g++.conf \
		/usr/share/qt/mkspecs/common/unix.conf \
		/usr/share/qt/mkspecs/common/linux.conf \
		/usr/share/qt/mkspecs/qconfig.pri \
		/usr/share/qt/mkspecs/features/qt_functions.prf \
		/usr/share/qt/mkspecs/features/qt_config.prf \
		/usr/share/qt/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt/mkspecs/features/default_pre.prf \
		/usr/share/qt/mkspecs/features/debug.prf \
		/usr/share/qt/mkspecs/features/default_post.prf \
		/usr/share/qt/mkspecs/features/warn_on.prf \
		/usr/share/qt/mkspecs/features/qt.prf \
		/usr/share/qt/mkspecs/features/unix/thread.prf \
		/usr/share/qt/mkspecs/features/moc.prf \
		/usr/share/qt/mkspecs/features/resources.prf \
		/usr/share/qt/mkspecs/features/uic.prf \
		/usr/share/qt/mkspecs/features/yacc.prf \
		/usr/share/qt/mkspecs/features/lex.prf \
		/usr/share/qt/mkspecs/features/include_source_dir.prf \
		lightgadu.pro
QMAKE_TARGET  = lightgadu
DESTDIR       = 
TARGET        = lightgadu

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_lgaddcontactwindow.h ui_lgchatwindow.h ui_mainwindow.h ui_lgsettingswindow.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: lightgadu.pro  /usr/share/qt/mkspecs/linux-g++-64/qmake.conf /usr/share/qt/mkspecs/common/g++.conf \
		/usr/share/qt/mkspecs/common/unix.conf \
		/usr/share/qt/mkspecs/common/linux.conf \
		/usr/share/qt/mkspecs/qconfig.pri \
		/usr/share/qt/mkspecs/features/qt_functions.prf \
		/usr/share/qt/mkspecs/features/qt_config.prf \
		/usr/share/qt/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt/mkspecs/features/default_pre.prf \
		/usr/share/qt/mkspecs/features/debug.prf \
		/usr/share/qt/mkspecs/features/default_post.prf \
		/usr/share/qt/mkspecs/features/warn_on.prf \
		/usr/share/qt/mkspecs/features/qt.prf \
		/usr/share/qt/mkspecs/features/unix/thread.prf \
		/usr/share/qt/mkspecs/features/moc.prf \
		/usr/share/qt/mkspecs/features/resources.prf \
		/usr/share/qt/mkspecs/features/uic.prf \
		/usr/share/qt/mkspecs/features/yacc.prf \
		/usr/share/qt/mkspecs/features/lex.prf \
		/usr/share/qt/mkspecs/features/include_source_dir.prf \
		/usr/lib/libQtSql.prl \
		/usr/lib/libQtGui.prl \
		/usr/lib/libQtCore.prl
	$(QMAKE) -spec /usr/share/qt/mkspecs/linux-g++-64 -unix CONFIG+=debug -o Makefile lightgadu.pro
/usr/share/qt/mkspecs/common/g++.conf:
/usr/share/qt/mkspecs/common/unix.conf:
/usr/share/qt/mkspecs/common/linux.conf:
/usr/share/qt/mkspecs/qconfig.pri:
/usr/share/qt/mkspecs/features/qt_functions.prf:
/usr/share/qt/mkspecs/features/qt_config.prf:
/usr/share/qt/mkspecs/features/exclusive_builds.prf:
/usr/share/qt/mkspecs/features/default_pre.prf:
/usr/share/qt/mkspecs/features/debug.prf:
/usr/share/qt/mkspecs/features/default_post.prf:
/usr/share/qt/mkspecs/features/warn_on.prf:
/usr/share/qt/mkspecs/features/qt.prf:
/usr/share/qt/mkspecs/features/unix/thread.prf:
/usr/share/qt/mkspecs/features/moc.prf:
/usr/share/qt/mkspecs/features/resources.prf:
/usr/share/qt/mkspecs/features/uic.prf:
/usr/share/qt/mkspecs/features/yacc.prf:
/usr/share/qt/mkspecs/features/lex.prf:
/usr/share/qt/mkspecs/features/include_source_dir.prf:
/usr/lib/libQtSql.prl:
/usr/lib/libQtGui.prl:
/usr/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec /usr/share/qt/mkspecs/linux-g++-64 -unix CONFIG+=debug -o Makefile lightgadu.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/lightgadu1.0.0 || $(MKDIR) .tmp/lightgadu1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/lightgadu1.0.0/ && $(COPY_FILE) --parents contactlistentry.h lgaddcontactwindow.h lgchatwindow.h lgconnectionthread.h lgcontactlist.h mainwindow.h lgbuddylistmenu.h lgsettingswindow.h .tmp/lightgadu1.0.0/ && $(COPY_FILE) --parents contactlistentry.cpp lgaddcontactwindow.cpp lgchatwindow.cpp lgconnectionthread.cpp lgcontactlist.cpp main.cpp mainwindow.cpp lgbuddylistmenu.cpp lgsettingswindow.cpp .tmp/lightgadu1.0.0/ && $(COPY_FILE) --parents lgaddcontactwindow.ui lgchatwindow.ui mainwindow.ui lgsettingswindow.ui .tmp/lightgadu1.0.0/ && (cd `dirname .tmp/lightgadu1.0.0` && $(TAR) lightgadu1.0.0.tar lightgadu1.0.0 && $(COMPRESS) lightgadu1.0.0.tar) && $(MOVE) `dirname .tmp/lightgadu1.0.0`/lightgadu1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/lightgadu1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_lgaddcontactwindow.cpp moc_lgchatwindow.cpp moc_lgconnectionthread.cpp moc_lgcontactlist.cpp moc_mainwindow.cpp moc_lgbuddylistmenu.cpp moc_lgsettingswindow.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_lgaddcontactwindow.cpp moc_lgchatwindow.cpp moc_lgconnectionthread.cpp moc_lgcontactlist.cpp moc_mainwindow.cpp moc_lgbuddylistmenu.cpp moc_lgsettingswindow.cpp
moc_lgaddcontactwindow.cpp: lgaddcontactwindow.h
	/usr/bin/moc $(DEFINES) $(INCPATH) lgaddcontactwindow.h -o moc_lgaddcontactwindow.cpp

moc_lgchatwindow.cpp: lgchatwindow.h
	/usr/bin/moc $(DEFINES) $(INCPATH) lgchatwindow.h -o moc_lgchatwindow.cpp

moc_lgconnectionthread.cpp: lgconnectionthread.h
	/usr/bin/moc $(DEFINES) $(INCPATH) lgconnectionthread.h -o moc_lgconnectionthread.cpp

moc_lgcontactlist.cpp: lgcontactlist.h
	/usr/bin/moc $(DEFINES) $(INCPATH) lgcontactlist.h -o moc_lgcontactlist.cpp

moc_mainwindow.cpp: lgcontactlist.h \
		lgchatwindow.h \
		lgconnectionthread.h \
		lgaddcontactwindow.h \
		lgbuddylistmenu.h \
		lgsettingswindow.h \
		mainwindow.h
	/usr/bin/moc $(DEFINES) $(INCPATH) mainwindow.h -o moc_mainwindow.cpp

moc_lgbuddylistmenu.cpp: lgbuddylistmenu.h
	/usr/bin/moc $(DEFINES) $(INCPATH) lgbuddylistmenu.h -o moc_lgbuddylistmenu.cpp

moc_lgsettingswindow.cpp: lgsettingswindow.h
	/usr/bin/moc $(DEFINES) $(INCPATH) lgsettingswindow.h -o moc_lgsettingswindow.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_lgaddcontactwindow.h ui_lgchatwindow.h ui_mainwindow.h ui_lgsettingswindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui_lgaddcontactwindow.h ui_lgchatwindow.h ui_mainwindow.h ui_lgsettingswindow.h
ui_lgaddcontactwindow.h: lgaddcontactwindow.ui
	/usr/bin/uic lgaddcontactwindow.ui -o ui_lgaddcontactwindow.h

ui_lgchatwindow.h: lgchatwindow.ui
	/usr/bin/uic lgchatwindow.ui -o ui_lgchatwindow.h

ui_mainwindow.h: mainwindow.ui
	/usr/bin/uic mainwindow.ui -o ui_mainwindow.h

ui_lgsettingswindow.h: lgsettingswindow.ui
	/usr/bin/uic lgsettingswindow.ui -o ui_lgsettingswindow.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

contactlistentry.o: contactlistentry.cpp contactlistentry.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o contactlistentry.o contactlistentry.cpp

lgaddcontactwindow.o: lgaddcontactwindow.cpp lgaddcontactwindow.h \
		ui_lgaddcontactwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o lgaddcontactwindow.o lgaddcontactwindow.cpp

lgchatwindow.o: lgchatwindow.cpp lgchatwindow.h \
		ui_lgchatwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o lgchatwindow.o lgchatwindow.cpp

lgconnectionthread.o: lgconnectionthread.cpp lgconnectionthread.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o lgconnectionthread.o lgconnectionthread.cpp

lgcontactlist.o: lgcontactlist.cpp lgcontactlist.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o lgcontactlist.o lgcontactlist.cpp

main.o: main.cpp mainwindow.h \
		lgcontactlist.h \
		lgchatwindow.h \
		lgconnectionthread.h \
		lgaddcontactwindow.h \
		lgbuddylistmenu.h \
		lgsettingswindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		lgcontactlist.h \
		lgchatwindow.h \
		lgconnectionthread.h \
		lgaddcontactwindow.h \
		lgbuddylistmenu.h \
		lgsettingswindow.h \
		ui_mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

lgbuddylistmenu.o: lgbuddylistmenu.cpp lgbuddylistmenu.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o lgbuddylistmenu.o lgbuddylistmenu.cpp

lgsettingswindow.o: lgsettingswindow.cpp lgsettingswindow.h \
		ui_lgsettingswindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o lgsettingswindow.o lgsettingswindow.cpp

moc_lgaddcontactwindow.o: moc_lgaddcontactwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_lgaddcontactwindow.o moc_lgaddcontactwindow.cpp

moc_lgchatwindow.o: moc_lgchatwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_lgchatwindow.o moc_lgchatwindow.cpp

moc_lgconnectionthread.o: moc_lgconnectionthread.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_lgconnectionthread.o moc_lgconnectionthread.cpp

moc_lgcontactlist.o: moc_lgcontactlist.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_lgcontactlist.o moc_lgcontactlist.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_lgbuddylistmenu.o: moc_lgbuddylistmenu.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_lgbuddylistmenu.o moc_lgbuddylistmenu.cpp

moc_lgsettingswindow.o: moc_lgsettingswindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_lgsettingswindow.o moc_lgsettingswindow.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

